export const lessons = [
  {id:1,title:'认识你的第一张表',level:'入门',tag:'SELECT',task:'查询 products 表中的全部商品，返回全部列。',hint:'SELECT * FROM 表名 可以查看全部列。',starter:'-- 查询 products 表的全部商品\nSELECT\nFROM products;',solution:'SELECT * FROM products;',ordered:false},
  {id:2,title:'找一款合适的数码产品',level:'入门',tag:'WHERE',task:'查询分类为“数码”且价格低于 400 的商品，依次返回 name、price 两列。',hint:'用 WHERE 限定 category，用 AND 组合价格条件。字符串需要单引号。',starter:"SELECT name, price\nFROM products\nWHERE ;",solution:"SELECT name, price FROM products WHERE category = '数码' AND price < 400;",ordered:false},
  {id:3,title:'价格榜的前三名',level:'入门',tag:'ORDER BY',task:'依次返回 name、price，按价格从高到低选出最贵的 3 款商品。',hint:'ORDER BY price DESC 按降序排列；LIMIT 3 只取三行。',starter:'SELECT name, price\nFROM products\nORDER BY\nLIMIT 3;',solution:'SELECT name, price FROM products ORDER BY price DESC LIMIT 3;',ordered:true},
  {id:4,title:'每个分类有多少商品',level:'基础',tag:'GROUP BY',task:'按分类分组，依次返回 category 和每类商品数量，按 category 升序排列。',hint:'COUNT(*) 统计行数，用 GROUP BY category 分组。',starter:'SELECT category,\nFROM products\nGROUP BY category\nORDER BY category;',solution:'SELECT category, COUNT(*) AS product_count FROM products GROUP BY category ORDER BY category;',ordered:true},
  {id:5,title:'平均价格更高的分类',level:'基础',tag:'HAVING',task:'依次返回 category、平均价格（四舍五入至 2 位小数），只保留平均价格超过 150 的分类。',hint:'聚合后的筛选用 HAVING AVG(price) > 150；ROUND(AVG(price), 2) 保留两位小数。',starter:'SELECT category,\nFROM products\nGROUP BY category\nHAVING ;',solution:'SELECT category, ROUND(AVG(price), 2) AS avg_price FROM products GROUP BY category HAVING AVG(price) > 150;',ordered:false},
  {id:6,title:'每张订单来自谁',level:'进阶',tag:'INNER JOIN',task:'关联 orders 和 customers，依次返回订单 id、客户 name、订单 status，按订单 id 升序排列。',hint:'orders.customer_id 对应 customers.id。使用表别名 o、c 可以简化语句。',starter:'SELECT o.id, c.name, o.status\nFROM orders AS o\nJOIN customers AS c ON\nORDER BY o.id;',solution:'SELECT o.id, c.name, o.status FROM orders o INNER JOIN customers c ON o.customer_id = c.id ORDER BY o.id;',ordered:true},
  {id:7,title:'还没有下单的客户',level:'进阶',tag:'LEFT JOIN',task:'找出没有订单的客户，只返回客户 name 这一列。',hint:'LEFT JOIN 保留全部客户；右表匹配不到的 orders.id 为 NULL。',starter:'SELECT c.name\nFROM customers AS c\nLEFT JOIN orders AS o ON c.id = o.customer_id\nWHERE ;',solution:'SELECT c.name FROM customers c LEFT JOIN orders o ON c.id = o.customer_id WHERE o.id IS NULL;',ordered:false},
  {id:8,title:'比平均价格更贵',level:'进阶',tag:'SUBQUERY',task:'找出价格高于全部商品平均价格的商品，依次返回 name、price，按价格从高到低排列。',hint:'子查询 SELECT AVG(price) FROM products 可以作为 WHERE price > 后的值。',starter:'SELECT name, price\nFROM products\nWHERE price > (\n  \n)\nORDER BY price DESC;',solution:'SELECT name, price FROM products WHERE price > (SELECT AVG(price) FROM products) ORDER BY price DESC;',ordered:true},
  {id:9,title:'算一算每张订单的金额',level:'挑战',tag:'SUM · JOIN',task:'按订单汇总明细金额，依次返回 order_id 和金额（quantity × unit_price 的总和），按 order_id 升序排列。',hint:'直接在 order_items 上 GROUP BY order_id，SUM(quantity * unit_price) 即是订单金额。',starter:'SELECT order_id,\nFROM order_items\nGROUP BY order_id\nORDER BY order_id;',solution:'SELECT order_id, SUM(quantity * unit_price) AS total FROM order_items GROUP BY order_id ORDER BY order_id;',ordered:true},
  {id:10,title:'各分类的价格排名',level:'挑战',tag:'WINDOW',task:'依次返回 category、name、price、分类内价格排名。用 DENSE_RANK 按分类内价格降序排名，最后按 category 升序、price 降序排列。',hint:'DENSE_RANK() OVER (PARTITION BY category ORDER BY price DESC) 为每个分类独立排名。MySQL 8 支持窗口函数。',starter:'SELECT\n  category, name, price,\n  DENSE_RANK() OVER (\n    \n  ) AS price_rank\nFROM products\nORDER BY category, price DESC;',solution:'SELECT category, name, price, DENSE_RANK() OVER (PARTITION BY category ORDER BY price DESC) AS price_rank FROM products ORDER BY category, price DESC;',ordered:true}
];

export const templates = [
  {name:'建表与写入',sql:"CREATE TABLE IF NOT EXISTS my_notes (\n  id INT PRIMARY KEY AUTO_INCREMENT,\n  content VARCHAR(100) NOT NULL,\n  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n);\n\nINSERT INTO my_notes (content)\nVALUES ('今天开始练习 SQL');\n\nSELECT * FROM my_notes;"},
  {name:'事务：更新后回滚',sql:"-- InnoDB 的 UPDATE 支持回滚；DDL 会隐式提交\nSTART TRANSACTION;\n\nUPDATE products\nSET price = price + 10\nWHERE id = 1;\n\nSELECT id, name, price FROM products WHERE id = 1;\nROLLBACK;\nSELECT id, name, price FROM products WHERE id = 1;"},
  {name:'查看表结构',sql:'SHOW TABLES;\nDESCRIBE products;\nSHOW CREATE TABLE products;'},
  {name:'修改与删除自己的记录',sql:"-- 先运行“建表与写入”模板\nUPDATE my_notes SET content = '已经学会 UPDATE' WHERE id = 1;\nSELECT * FROM my_notes;\n-- 需要删除时，取消下面一行的注释\n-- DELETE FROM my_notes WHERE id = 1;"}
];
