import {Capacitor,registerPlugin} from '@capacitor/core';
import {Preferences} from '@capacitor/preferences';
import {Filesystem,Directory,Encoding} from '@capacitor/filesystem';
import {Share} from '@capacitor/share';
import seed from '../seed/practice.sql?raw';
import questionRows from '../seed/questions.json';
import {templates as oldTemplates} from '../mobile/lessons.js';
import {createStartup} from './startup.js';
const Lab=registerPlugin('OfflineLab');
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uuid=()=>crypto.randomUUID(),quote=s=>'`'+s.replaceAll('`','``')+'`';
const defaults="-- 自由编程：可以替换成自己的数据库和表\nCREATE DATABASE IF NOT EXISTS my_lab\n  CHARACTER SET utf8mb4;\nUSE my_lab;\n\nCREATE TABLE IF NOT EXISTS notes (\n  id INT PRIMARY KEY AUTO_INCREMENT,\n  content VARCHAR(200) NOT NULL\n);\nINSERT INTO notes (content) VALUES ('我的第一次实验');\nSELECT * FROM notes;";
let info=null,projectId='',session='A',draft=null,result=null,resultIndex=0,saveTimer,toastTimer,opening=false;const running={A:false,B:false},sessionInfo={},sessionResults={};
let saveQueue=Promise.resolve();
const native=Capacitor.getPlatform()==='android';
const startup=createStartup(Lab,native);
window.addEventListener('unhandledrejection',e=>{toast(e.reason?.message||'操作未完成，请重试',true);});
const icon=path=>'<svg viewBox="0 0 24 24" aria-hidden="true">'+path+'</svg>';
const symbols={upload:'<path d="M12 16V3m-5 5 5-5 5 5M4 15v5a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-5"/>',download:'<path d="M12 3v13m-5-5 5 5 5-5M4 16v4a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-4"/>',database:'<ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v7c0 4 16 4 16 0V5M4 12v7c0 4 16 4 16 0v-7"/>',file:'<path d="M14 3H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9Zm0 0v6h6M8 14h8m-8 3h5"/>',history:'<path d="M3 11a9 9 0 1 1 2 7M3 4v7h7m2-4v6l4 2"/>',code:'<path d="m7 7-5 5 5 5m10-10 5 5-5 5M14 4l-4 16"/>',log:'<rect x="4" y="3" width="16" height="18" rx="3"/><path d="M8 8h8M8 12h8M8 16h5"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v.1"/>'};
for(const [id,name,subtitle] of [['import-sql','upload','从文件打开你的脚本'],['export-sql','download','保存这次编程灵感'],['export-project','database','库表与数据，一起备份'],['import-data','file','CSV 等本地数据文件'],['history','history','回看每一次实验'],['templates','code','查询、事务与存储过程'],['engine-log','log','查看本机运行状态'],['licenses','info','引擎与组件许可'],['account','database','切换 MySQL 用户，练习授权']]){const button=$('#'+id),label=button.textContent;button.innerHTML='<span class="tool-icon">'+icon(symbols[name])+'</span><span class="tool-copy">'+esc(label)+'<small>'+subtitle+'</small></span>';}
$('#run').innerHTML=icon('<path d="m8 5 10 7-10 7Z"/>')+'运行 SQL';
$('#export-result').innerHTML=icon(symbols.download)+'CSV';
let fullViewport=window.visualViewport?.height||window.innerHeight;
function keyboardLayout(){const height=window.visualViewport?.height||window.innerHeight;fullViewport=Math.max(fullViewport,height);const input=document.activeElement?.matches('textarea,input:not([type=file])'),open=fullViewport-height>120&&(input||document.body.classList.contains('keyboard-open')),editing=document.activeElement?.id==='editor'||(!input&&document.body.classList.contains('editor-typing'));document.body.classList.toggle('keyboard-open',!!open);document.body.classList.toggle('editor-typing',!!open&&!!editing);document.documentElement.style.setProperty('--keyboard-viewport-height',height+'px');}
window.visualViewport?.addEventListener('resize',keyboardLayout);window.addEventListener('resize',keyboardLayout);document.addEventListener('focusin',keyboardLayout);document.addEventListener('focusout',()=>setTimeout(keyboardLayout,100));window.addEventListener('orientationchange',()=>{fullViewport=window.visualViewport?.height||window.innerHeight;keyboardLayout();});
async function pref(name,fallback){const {value}=await Preferences.get({key:'lab:'+name});try{return value?JSON.parse(value):fallback;}catch{return fallback;}}
const put=(name,value)=>Preferences.set({key:'lab:'+name,value:JSON.stringify(value)});
function toast(message,error=false){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').classList.toggle('error',error);$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,4500);}
function show(title,html){$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=html;$('#dialog').showModal();}
const close=()=>$('#dialog').close();
function ready(value){$('#engine-dot').classList.toggle('ready',value);$('#run').disabled=!value||running[session];}
function status(text){$('#engine-status').textContent=text;startup.update(text);}
function tab(){return draft?.tabs.find(t=>t.id===draft.active);}
async function save(){if(!draft||!projectId)return;clearTimeout(saveTimer);const id=projectId,snapshot=JSON.stringify(draft);const pending=saveQueue.catch(()=>{}).then(()=>Preferences.set({key:'lab:draft:'+id,value:snapshot}));saveQueue=pending;await pending;if(id===projectId&&JSON.stringify(draft)===snapshot)$('#draft').textContent='已保存在手机';}
document.addEventListener('visibilitychange',()=>{if(document.hidden)void save().catch(e=>toast(e.message,true));});
function changed(){if(!draft)return;tab().sql=$('#editor').value;$('#draft').textContent='正在保存…';clearTimeout(saveTimer);saveTimer=setTimeout(()=>save().catch(e=>toast(e.message,true)),350);lines();}
function lines(){$('#lines').textContent=Array.from({length:$('#editor').value.split('\n').length},(_,i)=>i+1).join('\n');$('#lines').scrollTop=$('#editor').scrollTop;}
function tabs(){if(!draft)return;$('#tabs').innerHTML=draft.tabs.map(t=>`<button data-tab="${t.id}" class="${t.id===draft.active?'active':''}">${esc(t.name)}</button>`).join('')+'<button data-new-tab aria-label="新脚本">＋</button>';$('#editor').value=tab().sql;lines();}
async function addTab(sql='',name){if(!draft)return;const value={id:uuid(),name:name||'脚本 '+(draft.tabs.length+1),sql};draft.tabs.push(value);draft.active=value.id;tabs();await save();}
function sessionState(value){if(value)sessionInfo[value.name]=value;const current=sessionInfo[session];$('#transaction').textContent=running[session]?'正在运行…':current?(current.inTransaction?'事务未提交':`连接 ${current.connectionId}`):'未连接';$('#transaction').classList.toggle('pending',!!current?.inTransaction);document.querySelectorAll('[data-session]').forEach(b=>b.classList.toggle('selected',b.dataset.session===session));$('#run').disabled=!info||running[session];$('#cancel').hidden=!running[session];}
async function projectList(){const {projects}=await Lab.projects();$('#project-list').innerHTML=projects.map(p=>`<div class="list-card"><h3>${esc(p.name)} ${p.id===projectId?'· 当前':''}</h3><small>${new Date(p.created).toLocaleDateString('zh-CN')} · 独立数据目录</small><div class="list-actions"><button data-open="${p.id}">打开实验</button><button data-rename="${p.id}" data-name="${esc(p.name)}">重命名</button><button data-delete="${p.id}" class="danger">删除</button></div></div>`).join('');return projects;}
async function openProject(id){if(opening||running.A||running.B){toast('请先结束正在运行的 SQL');return;}await save();opening=true;ready(false);info=null;projectId=id;sessionInfo.A=null;sessionInfo.B=null;sessionResults.A=null;sessionResults.B=null;sessionState();status('正在打开实验…');try{draft=await pref('draft:'+id,null);if(!draft?.tabs?.length){const t={id:uuid(),name:'脚本 01',sql:defaults};draft={tabs:[t],active:t.id,history:[]};}if(!draft.tabs.some(t=>t.id===draft.active))draft.active=draft.tabs[0].id;tabs();info=await Lab.boot({id});$('#project-name').textContent=info.projectName;$('#engine-title').textContent=info.engine+' '+info.version;for(const value of info.sessions)sessionState(value);status('离线已就绪 · 数据保存在当前手机');ready(true);result=null;renderResults();await put('active',id);await projectList();await schema();}catch(error){status('引擎未启动，可在工具箱查看日志');toast(error.message,true);}finally{opening=false;}}
async function schema(){if(!info)return;try{const data=await Lab.schema();$('#schema-list').innerHTML=data.databases.map(row=>{const name=Object.values(row)[0],tables=data.tables.filter(t=>t.db===name);return `<div class="list-card"><h3>${esc(name)}</h3><div class="list-actions"><button data-use="${esc(name)}">使用此库</button></div>${tables.map(t=>`<div class="schema-table"><span>${esc(t.name)} <small>${esc(t.kind)}</small></span><button data-preview="${esc(name)}" data-table="${esc(t.name)}">查看</button></div>`).join('')||'<small>系统库或尚未创建表</small>'}</div>`;}).join('');}catch(error){toast(error.message,true);}}
function page(name){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===name));document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('selected',b.dataset.page===name));if(name==='projects'&&native)void projectList();if(name==='schema')void schema();}
async function run(){if(!info||running[session])return;const editor=$('#editor'),selected=editor.selectionStart!==editor.selectionEnd?editor.value.slice(editor.selectionStart,editor.selectionEnd):editor.value;if(!selected.trim()){toast('先输入 SQL');return;}const name=session,pid=projectId,wasTyping=document.body.classList.contains('keyboard-open');if(wasTyping){editor.blur();void Lab.hideKeyboard().catch(()=>{});}running[name]=true;sessionState();const start=Date.now();try{const data=await Lab.execute({session:name,sql:selected,limit:Number($('#limit').value)});sessionState(data.session);if(pid===projectId){sessionResults[name]=data;if(name===session){result=data;resultIndex=Math.max(0,data.statements.length-1);renderResults();if(wasTyping&&$('#work').classList.contains('active'))setTimeout(()=>$('#results').scrollIntoView({behavior:'smooth',block:'start'}),250);}draft.history.unshift({sql:selected,time:Date.now(),session:name,success:!data.hasError,duration:data.executionTime});draft.history=draft.history.slice(0,200);await save();}await schema();}catch(error){sessionInfo[name]=null;toast(error.message,true);$('#duration').textContent=(Date.now()-start)+' ms';}finally{running[name]=false;sessionState();}}
function renderResults(){const statements=result?.statements||[];$('#duration').textContent=result?(result.cancelled?'已取消 · ':'')+result.executionTime+' ms':'';$('#result-tabs').innerHTML=statements.map((s,i)=>`<button data-result="${i}" class="${i===resultIndex?'selected':''}">${i+1}${s.error?' · 错误':''}</button>`).join('');const value=statements[resultIndex];if(!value){$('#results').innerHTML='<div class="empty"><span>⌘</span><strong>从一个想法开始</strong><p>自己建表、存数据、运行 SQL。<br>实验数据会保存在当前手机。</p></div>';return;}if(value.error){$('#results').innerHTML=`<div class="result-message error">${esc(value.errorCode)} · ${esc(value.sqlState)} · 脚本第 ${value.startLine} 行<br>${esc(value.error)}</div>`;return;}if(!value.fields?.length){$('#results').innerHTML=`<div class="result-message">✓ 执行成功<br>影响 ${value.affectedRows||0} 行${value.warnings?'<br>警告 '+value.warnings+' 条，可运行 SHOW WARNINGS 查看':''}</div>`;return;}$('#results').innerHTML=`<table><thead><tr>${value.fields.map(f=>`<th>${esc(f)}</th>`).join('')}</tr></thead><tbody>${value.rows.map(row=>`<tr>${value.fields.map(f=>`<td class="${row[f]===null?'null':''}">${row[f]===null?'NULL':esc(row[f])}</td>`).join('')}</tr>`).join('')}</tbody></table><div class="result-summary">${value.totalRows} 行${value.truncated?' · 当前仅显示部分结果':''}${value.warnings?' · '+value.warnings+' 条警告':''}</div>`;}
async function download(name,content){name=name.replace(/[\\/:*?"<>|\x00-\x1f]/g,'_').slice(0,100);const {uri}=await Filesystem.writeFile({path:name,data:content,directory:Directory.Cache,encoding:Encoding.UTF8});await Share.share({title:name,url:uri,dialogTitle:'保存或分享文件'});}
function nameDialog(title,initial,action){show(title,`<label>项目名称</label><input id="name-input" maxlength="80" value="${esc(initial)}"><button id="name-confirm" class="primary">确定</button>`);$('#name-confirm').onclick=async()=>{try{await action($('#name-input').value);close();}catch(error){toast(error.message,true);}};}
$('#create-project').onclick=()=>nameDialog('新建自由实验','新的实验',async name=>{const p=await Lab.createProject({name});await openProject(p.id);page('work');});
$('#project-list').onclick=async event=>{const b=event.target.closest('button');if(!b)return;if(b.dataset.open){if(sessionInfo.A?.inTransaction||sessionInfo.B?.inTransaction){if(!confirm('当前有未提交事务。切换项目会回滚这些修改，是否继续？'))return;}await openProject(b.dataset.open);page('work');}if(b.dataset.rename)nameDialog('重命名项目',b.dataset.name,async name=>{await Lab.renameProject({id:b.dataset.rename,name});await projectList();if(b.dataset.rename===projectId){$('#project-name').textContent=name;info.projectName=name;}});if(b.dataset.delete&&confirm('删除此实验项目及其全部数据库？此操作无法撤销，请先导出备份。')){await save();await Lab.deleteProject({id:b.dataset.delete});await Preferences.remove({key:'lab:draft:'+b.dataset.delete});if(b.dataset.delete===projectId){info=null;projectId='';draft=null;ready(false);const all=await projectList();if(all.length)await openProject(all[0].id);else{const p=await Lab.createProject({name:'我的实验'});await openProject(p.id);}}else await projectList();}};
$('#schema-list').onclick=async event=>{const b=event.target.closest('button');if(!b)return;if(b.dataset.use){await addTab('USE '+quote(b.dataset.use)+';','切换数据库');page('work');}if(b.dataset.preview){await addTab('SELECT * FROM '+quote(b.dataset.preview)+'.'+quote(b.dataset.table)+' LIMIT 200;','查看 '+b.dataset.table);page('work');}};
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>page(b.dataset.page));$('#project-menu').onclick=()=>page('projects');
document.querySelectorAll('[data-session]').forEach(b=>b.onclick=()=>{session=b.dataset.session;result=sessionResults[session]||null;resultIndex=Math.max(0,(result?.statements.length||1)-1);renderResults();sessionState();});
$('#editor').oninput=changed;$('#editor').onscroll=()=>$('#lines').scrollTop=$('#editor').scrollTop;$('#editor').onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();void run();}if(e.key==='Tab'){e.preventDefault();const editor=$('#editor');editor.setRangeText('  ',editor.selectionStart,editor.selectionEnd,'end');changed();}};
$('#tabs').onclick=async event=>{const b=event.target.closest('button');if(b?.dataset.tab){await save();draft.active=b.dataset.tab;tabs();await save();}if(b?.hasAttribute('data-new-tab'))await addTab();};$('#new-tab').onclick=()=>addTab();
document.querySelectorAll('[data-insert]').forEach(b=>b.onclick=()=>{const e=$('#editor');e.setRangeText(b.dataset.insert,e.selectionStart,e.selectionEnd,'end');e.focus();changed();});
$('#run').onclick=run;$('#cancel').onclick=()=>Lab.cancel({session}).catch(e=>toast(e.message,true));$('#refresh-schema').onclick=schema;
$('#reboot').onclick=async()=>{if(!projectId||opening)return;if(running.A||running.B){toast('请先取消执行');return;}if((sessionInfo.A?.inTransaction||sessionInfo.B?.inTransaction)&&!confirm('重连会回滚未提交事务，是否继续？'))return;await Lab.stop();await openProject(projectId);};
$('#account').onclick=()=>{if(!info){toast('请先等待本机引擎就绪');return;}show('会话 '+session+' · 数据库用户实验','<p>App 无需登录。这里仅用于 MySQL 用户与权限实验：先用 CREATE USER、GRANT 创建数据库用户，再切换当前会话验证授权。默认 root 是此项目的本机管理员。</p><label>数据库用户名</label><input id="user-input" value="root" autocomplete="off"><label>数据库密码（默认 root 留空即可）</label><input id="password-input" type="password" autocomplete="off"><label>初始数据库（可留空）</label><input id="database-input"><button id="connect-user" class="primary">切换此会话的数据库用户</button>');$('#connect-user').onclick=async()=>{if(running[session]){toast('请先结束此会话正在运行的 SQL');return;}if(sessionInfo[session]?.inTransaction&&!confirm('重新连接会回滚此会话的未提交事务，是否继续？'))return;const user=$('#user-input').value;try{const value=await Lab.connect({session,user,...($('#password-input').value?{password:$('#password-input').value}:user==='root'?{}:{password:''}),database:$('#database-input').value});sessionState(value);close();toast('会话已连接为 '+user);}catch(e){toast(e.message,true);}};};
$('#about').onclick=()=>show('关于 KaiserSQL',`<div class="about-art"><img src="${esc($('#about-brand').src)}" alt="KaiserSQL 手机 MySQL"></div><p class="about-edition">小蔡同学版 · 0.3.1</p><p>装进口袋的 MySQL 实验室。自由建库、建表、存数据，按自己的想法编程，也可以导入题库练习。</p><div class="about-features"><span>完全离线</span><span>无需登录</span><span>本机保存</span></div><p>内置 MySQL Community Server 8.0.45。启动插画与品牌图保存在安装包里。</p>`);
$('#result-tabs').onclick=e=>{const b=e.target.closest('button');if(b){resultIndex=Number(b.dataset.result);renderResults();}};
$('#export-result').onclick=async()=>{const v=result?.statements[resultIndex];if(!v?.fields?.length){toast('当前没有表格结果');return;}const cell=x=>{let text=x===null?'':String(x);if(typeof x==='string'&&/^[=+\-@\t\r]/.test(text))text="'"+text;return '"'+text.replaceAll('"','""')+'"';};await download('实验结果.csv','\ufeff'+[v.fields,...v.rows.map(row=>v.fields.map(f=>row[f]))].map(row=>row.map(cell).join(',')).join('\r\n'));};
$('#import-sql').onclick=()=>$('#sql-file').click();$('#sql-file').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>20*1024*1024)throw new Error('SQL 文件最多 20 MB');await addTab(await file.text(),file.name);page('work');toast('脚本已导入，点击运行后才会执行');}catch(error){toast(error.message,true);}};
$('#export-sql').onclick=()=>download((tab()?.name||'实验')+'.sql',tab()?.sql||'');
$('#history').onclick=()=>{show('执行历史',(draft?.history||[]).map((h,i)=>`<div class="list-card"><small>${new Date(h.time).toLocaleString('zh-CN')} · 会话 ${h.session} · ${h.success?'成功':'错误'}</small><pre>${esc(h.sql)}</pre><button data-history="${i}" class="quiet">打开脚本</button></div>`).join('')||'<p>还没有运行记录。</p>');$('#dialog-body').onclick=async e=>{const b=e.target.closest('[data-history]');if(b){await addTab(draft.history[Number(b.dataset.history)].sql,'历史脚本');close();page('work');}};};
const examples=[{name:'从空数据库开始',sql:defaults},{name:'存储过程与定界符',sql:"CREATE DATABASE IF NOT EXISTS procedure_lab;\nUSE procedure_lab;\nDROP PROCEDURE IF EXISTS count_to;\nDELIMITER $$\nCREATE PROCEDURE count_to(IN n INT)\nBEGIN\n  DECLARE i INT DEFAULT 0;\n  WHILE i < n DO\n    SET i = i + 1;\n  END WHILE;\n  SELECT i AS 最终计数;\nEND$$\nDELIMITER ;\nCALL count_to(5);"},{name:'事务与会话实验',sql:"-- 两个会话先分别执行 USE my_lab;\n-- 会话 A：开始事务，写入后先不提交\nUSE my_lab;\nSTART TRANSACTION;\nINSERT INTO notes (content) VALUES ('还没有提交');\nSELECT * FROM notes;\n-- 会话 B：执行 USE my_lab; SELECT * FROM notes;\n-- 回到 A，再执行 COMMIT; 或 ROLLBACK;"},...oldTemplates];
$('#templates').onclick=()=>{show('实验示例',examples.map((v,i)=>`<div class="list-card"><h3>${esc(v.name)}</h3><button data-example="${i}" class="quiet">打开脚本</button></div>`).join(''));$('#dialog-body').onclick=async e=>{const b=e.target.closest('[data-example]');if(b){const v=examples[Number(b.dataset.example)];await addTab(v.sql,v.name);close();page('work');}};};
$('#engine-log').onclick=async()=>{if(!projectId)return;const {log}=await Lab.logs({id:projectId});show('引擎日志','<pre>'+esc(log||'暂无日志')+'</pre>');};
$('#licenses').onclick=async()=>{const response=await fetch('./open-source-licenses.txt');show('开源说明','<p>内置 MySQL Community Server 8.0.45、Oracle Linux 运行库与 Termux PRoot。详细来源和校验值见项目源码的 offline-runtime-lock.json。</p><pre>'+esc(await response.text())+'</pre>');};
$('#export-project').onclick=async()=>{try{const {uri}=await Lab.dump({id:projectId});await Share.share({title:'实验数据库备份',url:uri,dialogTitle:'保存或分享 SQL 备份'});}catch(e){toast(e.message,true);}};
$('#import-data').onclick=()=>$('#data-file').click();$('#data-file').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>20*1024*1024)throw new Error('此入口一次最多导入 20 MB 文件');const bytes=new Uint8Array(await file.arrayBuffer());if(bytes.length>20*1024*1024)throw new Error('此入口一次最多导入 20 MB 文件');let text='';for(let i=0;i<bytes.length;i+=32768)text+=String.fromCharCode(...bytes.subarray(i,i+32768));const {path}=await Lab.importFile({name:file.name,data:btoa(text)});show('文件已保存到当前项目',`<p>可在 SQL 中使用这个文件路径：</p><pre>${esc(path)}</pre><p>例如使用 LOAD DATA INFILE 导入 CSV。文件不会自动执行。</p>`);}catch(error){toast(error.message,true);}};
// Local question-bank module registers its UI after the workspace has initialized.
const stateAccess={Lab,seed,questionRows,esc,show,close,toast,addTab,page,openProject,projectList,pref,put,get projectId(){return projectId;},get info(){return info;},get sql(){return $('#editor').value;}};
import('./practice.js').then(module=>module.setupPractice(stateAccess)).catch(e=>toast(e.message,true));
window.addEventListener('pagehide',()=>void save());
if(native){try{await Lab.addListener('progress',value=>status(value.message));const all=await projectList(),last=await pref('active','');const id=all.some(p=>p.id===last)?last:all[0]?.id||(await Lab.createProject({name:'我的第一个实验'})).id;await openProject(id);}catch(error){status('引擎准备失败');toast(error.message,true);}finally{startup.finish(!!info);}}else{status('请安装安卓离线 APK；浏览器仅用于界面预览');$('#engine-title').textContent='安卓离线版本';$('#editor').value=defaults;lines();startup.finish();}
