import {unzipSync} from 'fflate';
const headers=['题目ID','数据集ID','题型','标题','难度','知识点','题干','起始SQL','参考答案SQL','检查SQL','要求排序','提示','解析'];
const decode=bytes=>{if(!bytes)throw new Error('题库缺少必要文件');return new TextDecoder('utf-8',{fatal:true}).decode(bytes);};
function unzip(bytes,max=100*1024*1024){let count=0,total=0;const names=new Set();return unzipSync(bytes,{filter(file){count++;total+=file.originalSize;if(count>100||total>max||file.originalSize>50*1024*1024)throw new Error('压缩包解压后超过大小或数量限制');if(names.has(file.name)||!file.name||file.name.includes('\\')||file.name.startsWith('/')||file.name.split('/').includes('..')||file.name.includes('\0')||/^[a-z]:/i.test(file.name))throw new Error('压缩包包含重复或不安全路径');names.add(file.name);return true;}});}
function xml(bytes){const text=decode(bytes);if(/<!DOCTYPE/i.test(text))throw new Error('Excel 不支持 DTD');const doc=new DOMParser().parseFromString(text,'application/xml');if(doc.getElementsByTagName('parsererror').length)throw new Error('Excel XML 无法读取');return doc;}
const nodes=(doc,name)=>[...doc.getElementsByTagNameNS('*',name)];
function sheet(files,name){const workbook=xml(files['xl/workbook.xml']),sheet=nodes(workbook,'sheet').find(s=>s.getAttribute('name')===name);if(!sheet)throw new Error('Excel 缺少题目工作表');const relation=sheet.getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','id')||sheet.getAttribute('r:id');const rel=nodes(xml(files['xl/_rels/workbook.xml.rels']),'Relationship').find(r=>r.getAttribute('Id')===relation);if(!rel||rel.getAttribute('TargetMode')==='External')throw new Error('Excel 工作表引用不正确');let path=rel.getAttribute('Target');path=path.startsWith('/')?path.slice(1):'xl/'+path;if(path.includes('..'))throw new Error('Excel 工作表路径不正确');const shared=files['xl/sharedStrings.xml']?nodes(xml(files['xl/sharedStrings.xml']),'si').map(si=>nodes(si,'t').map(t=>t.textContent).join('')):[];const document=xml(files[path]);if(nodes(document,'f').length||nodes(document,'hyperlink').length)throw new Error('题库不支持 Excel 公式或链接');const rows=new Map();let cellCount=0;for(const row of nodes(document,'row')){const r=Number(row.getAttribute('r'));if(!Number.isInteger(r)||r<1||r>1030)throw new Error('题目表最多支持 1000 道题');const values=new Map();for(const cell of nodes(row,'c')){if(++cellCount>40000)throw new Error('Excel 单元格超过限制');const ref=/^([A-Z]{1,3})(\d+)$/.exec(cell.getAttribute('r'));if(!ref||Number(ref[2])!==r)throw new Error('Excel 单元格坐标不正确');let col=0;for(const c of ref[1])col=col*26+c.charCodeAt(0)-64;if(col>30)throw new Error('题目表最多 30 列');const type=cell.getAttribute('t');let value=type==='inlineStr'?nodes(cell,'t').map(t=>t.textContent).join(''):nodes(cell,'v')[0]?.textContent||'';if(type==='s'){const index=Number(value);if(!Number.isInteger(index)||!(index in shared))throw new Error('Excel 字符串引用不正确');value=shared[index];}if(value.length>65536)throw new Error('题目单元格内容过长');values.set(col,value.trim());}rows.set(r,values);}return rows;}
function parseQuestion(row){const q={id:row['题目ID'],dataset:row['数据集ID'],type:row['题型'],title:row['标题'],level:row['难度'],tag:row['知识点'],task:row['题干'],starter:row['起始SQL'],answer:row['参考答案SQL'],checker:row['检查SQL'],ordered:row['要求排序']==='是',hint:row['提示'],explanation:row['解析']};if(!/^[a-zA-Z0-9_-]{1,60}$/.test(q.id)||!/^[a-zA-Z0-9_-]{1,60}$/.test(q.dataset)||!q.title||q.title.length>100||!q.task||!q.answer||!['查询','数据修改','建表'].includes(q.type)||!['是','否'].includes(row['要求排序']))throw new Error('题目 ID、类型、标题、答案或排序要求不正确');if(q.type!=='查询'&&!q.checker)throw new Error('数据修改和建表题需要检查 SQL');return q;}
export function parseBank(bytes){if(bytes.length>20*1024*1024)throw new Error('题库 ZIP 最多 20 MB');const files=unzip(bytes),m=JSON.parse(decode(files['bank.json']));if(m.formatVersion!==1||m.mysqlMajor!==8||!/^[a-zA-Z0-9_-]{1,60}$/.test(m.id)||!/^[a-zA-Z0-9._-]{1,40}$/.test(m.version)||!m.title||!Array.isArray(m.datasets)||m.datasets.length<1||m.datasets.length>10)throw new Error('题库清单不正确');const datasets={};for(const d of m.datasets){if(!/^[a-zA-Z0-9_-]{1,60}$/.test(d.id)||datasets[d.id]||!/^datasets\/[a-zA-Z0-9_.-]+\.sql$/.test(d.file)||!files[d.file]||files[d.file].length>1024*1024)throw new Error('数据集配置不正确');datasets[d.id]=decode(files[d.file]);}const rows=sheet(unzip(files[m.questionsFile||'questions.xlsx'],50*1024*1024),m.questionsSheet||'题目');const header=Number(m.headerRow||5),start=Number(m.dataStartRow||6);if(!Number.isInteger(header)||!Number.isInteger(start)||start<=header||start>1030||headers.some((v,i)=>rows.get(header)?.get(i+1)!==v))throw new Error('题目表头或数据行配置不正确');const questions=[],ids=new Set();for(const [index,values]of rows){if(index<start||!values.get(1))continue;const q=parseQuestion(Object.fromEntries(headers.map((h,i)=>[h,values.get(i+1)||''])));if(ids.has(q.id)||!datasets[q.dataset])throw new Error('题目重复或引用缺失数据集：'+q.id);ids.add(q.id);questions.push(q);}if(!questions.length||questions.length>1000)throw new Error('题库需要 1 至 1000 道题');return {id:m.id,version:m.version,title:m.title,datasets,questions};}
export async function setupPractice(app){
 const $=s=>document.querySelector(s),{esc}=app;
 let banks=await app.pref('banks',[]),solved=await app.pref('solved',[]),practiceProjects=await app.pref('practice-projects',{}),selected=null,activeQuestion=null,grading=false;
 const builtin={id:'pocket-mysql-ecommerce',version:'1.0.0',title:'电商 SQL 入门与进阶',datasets:{ecommerce:app.seed},questions:app.questionRows.map(parseQuestion)};
 if(!banks.some(b=>b.id===builtin.id&&b.version===builtin.version)){banks.unshift(builtin);await app.put('banks',banks);}
 function draw(){ $('#banks').innerHTML=banks.map((b,i)=>`<div class="list-card"><h3>${esc(b.title)}</h3><small>${esc(b.version)} · ${b.questions.length} 道题 · 手机内保存</small><div class="list-actions"><button data-bank="${i}">浏览题目</button></div></div>`).join('');$('#lesson-list').innerHTML=selected?`<h3>${esc(selected.title)}</h3>`+selected.questions.map((q,i)=>`<div class="list-card"><h3>${esc(q.title)} ${solved.includes(selected.id+'@'+selected.version+':'+q.id)?'✓':''}</h3><small>${esc(q.level)} · ${esc(q.tag)}</small><button data-question="${i}" class="quiet">开始练习</button></div>`).join(''):'';}
 $('#banks').onclick=e=>{const b=e.target.closest('[data-bank]');if(b){selected=banks[Number(b.dataset.bank)];draw();$('#lesson-list').scrollIntoView({behavior:'smooth'});}};
 async function startQuestion(q){if(!app.info){app.toast('请先启动本机引擎');return;}if(!confirm('练习将使用独立项目，并结束当前会话。已提交数据会保留，未提交事务会回滚。是否继续？'))return;const key=selected.id+'@'+selected.version+':'+q.dataset,all=await app.Lab.projects();let id=practiceProjects[key],initialize=false;if(!all.projects.some(p=>p.id===id)){id=(await app.Lab.createProject({name:'练习 · '+selected.title+' · '+q.dataset})).id;initialize=true;}
 await app.openProject(id);if(!app.info||app.info.projectId!==id)throw new Error('练习项目尚未启动');
 if(initialize){const dataset=selected.datasets[q.dataset].replace(/^\s*CREATE\s+DATABASE[^;]*;\s*/gim,'').replace(/^\s*USE\s+[^;]*;\s*/gim,'');const setup=await app.Lab.execute({session:'A',sql:'CREATE DATABASE practice CHARACTER SET utf8mb4; USE practice;\n'+dataset,limit:1});if(setup.hasError)throw new Error(setup.statements.find(s=>s.error)?.error||'数据集初始化失败');practiceProjects[key]=id;await app.put('practice-projects',practiceProjects);}else await app.Lab.execute({session:'A',sql:'USE practice;',limit:1});
 await app.addTab(q.starter,q.title);activeQuestion={q,bank:selected,projectId:id};app.page('work');showQuestion();}
 function showQuestion(){if(!activeQuestion)return;if(app.projectId!==activeQuestion.projectId){app.toast('请先回到该题目的练习项目');return;}const {q}=activeQuestion;app.show(q.title,`<p>${esc(q.task)}</p><p>${esc(q.hint)}</p><button id="grade-current" class="primary">离线提交当前脚本</button><button id="show-answer" class="quiet">查看参考答案与解析</button><p id="grade-message">判题使用独立初始数据，不读取当前实验表的修改。</p>`);$('#grade-current').onclick=async()=>{if(grading)return;grading=true;$('#grade-current').disabled=true;$('#grade-message').textContent='手机内正在判题…';try{const result=await app.Lab.grade({dataset:activeQuestion.bank.datasets[q.dataset],sql:app.sql,answer:q.answer,checker:q.checker,ordered:q.ordered});$('#grade-message').textContent=result.message;if(result.passed){const key=activeQuestion.bank.id+'@'+activeQuestion.bank.version+':'+q.id;if(!solved.includes(key))solved.push(key);await app.put('solved',solved);draw();}}catch(e){$('#grade-message').textContent=e.message;}finally{grading=false;$('#grade-current').disabled=false;}};$('#show-answer').onclick=()=>{app.show('参考答案与解析',`<pre>${esc(q.answer)}</pre><p>${esc(q.explanation)}</p><button id="use-answer" class="primary">打开参考脚本</button>`);$('#use-answer').onclick=async()=>{await app.addTab(q.answer,'参考 · '+q.title);app.close();app.page('work');};};}
 $('#lesson-list').onclick=e=>{const b=e.target.closest('[data-question]');if(b)startQuestion(selected.questions[Number(b.dataset.question)]).catch(e=>app.toast(e.message,true));};
 // A persistent entry is needed after the question dialog is closed to edit SQL.
 const submit=document.createElement('button');submit.textContent='当前练习';submit.className='quiet';submit.id='current-lesson';submit.hidden=true;$('#work .result-head').append(submit);submit.onclick=showQuestion;
 const observer=new MutationObserver(()=>submit.hidden=!activeQuestion);observer.observe($('#dialog-body'),{childList:true});
 $('#import-bank').onclick=()=>$('#bank-file').click();$('#bank-file').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>20*1024*1024)throw new Error('题库 ZIP 最多 20 MB');const bank=parseBank(new Uint8Array(await file.arrayBuffer()));if(banks.some(b=>b.id===bank.id&&b.version===bank.version))throw new Error('此题库版本已导入，请修改版本号');app.show('导入题库预览',`<p>${esc(bank.title)} · ${bank.questions.length} 道题</p><p>全部保存到手机，无需上传服务器。导入时会用实际 MySQL 校验参考答案。</p><button id="save-bank" class="primary">校验并导入</button><p id="import-status"></p>`);$('#save-bank').onclick=async()=>{if(!app.info){app.toast('请先启动本机引擎');return;}$('#save-bank').disabled=true;try{for(let i=0;i<bank.questions.length;i++){const q=bank.questions[i];$('#import-status').textContent=`校验 ${i+1} / ${bank.questions.length}`;const result=await app.Lab.grade({dataset:bank.datasets[q.dataset],sql:q.answer,answer:q.answer,checker:q.checker,ordered:q.ordered});if(!result.passed)throw new Error(q.id+'：'+result.message);}banks.push(bank);await app.put('banks',banks);draw();app.close();app.toast('题库已保存在手机');}catch(error){$('#import-status').textContent=error.message;$('#save-bank').disabled=false;}};}catch(error){app.toast(error.message,true);}};
 draw();
}
